package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name="comments"
    ,catalog="sbatko1"
)
public class Comments  implements java.io.Serializable {


     private Integer comId;
     private int comTskId;
     private int comUsrId;
     private String comComment;
     private Date comDate;

    public Comments() {
    }

	
    public Comments(int comTskId, int comUsrId) {
        this.comTskId = comTskId;
        this.comUsrId = comUsrId;
    }
    public Comments(int comTskId, int comUsrId, String comComment, Date comDate) {
       this.comTskId = comTskId;
       this.comUsrId = comUsrId;
       this.comComment = comComment;
       this.comDate = comDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="com_id", unique=true, nullable=false)
    public Integer getComId() {
        return this.comId;
    }
    
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    
    @Column(name="com_tsk_id", nullable=false)
    public int getComTskId() {
        return this.comTskId;
    }
    
    public void setComTskId(int comTskId) {
        this.comTskId = comTskId;
    }

    
    @Column(name="com_usr_id", nullable=false)
    public int getComUsrId() {
        return this.comUsrId;
    }
    
    public void setComUsrId(int comUsrId) {
        this.comUsrId = comUsrId;
    }

    
    @Column(name="com_comment", length=65535)
    public String getComComment() {
        return this.comComment;
    }
    
    public void setComComment(String comComment) {
        this.comComment = comComment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_date", length=19)
    public Date getComDate() {
        return this.comDate;
    }
    
    public void setComDate(Date comDate) {
        this.comDate = comDate;
    }




}


