package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Leaves generated by hbm2java
 */
@Entity
@Table(name="leaves"
    ,catalog="sbatko1"
)
public class Leaves  implements java.io.Serializable {


     private Integer leaId;
     private int leaUsrId;
     private Integer leaLtpId;
     private Date leaDay;
     private String leaReason;
     private Boolean leaStatus;
     private Integer leaWhoDecided;

    public Leaves() {
    }

	
    public Leaves(int leaUsrId, Date leaDay) {
        this.leaUsrId = leaUsrId;
        this.leaDay = leaDay;
    }
    public Leaves(int leaUsrId, Integer leaLtpId, Date leaDay, String leaReason, Boolean leaStatus, Integer leaWhoDecided) {
       this.leaUsrId = leaUsrId;
       this.leaLtpId = leaLtpId;
       this.leaDay = leaDay;
       this.leaReason = leaReason;
       this.leaStatus = leaStatus;
       this.leaWhoDecided = leaWhoDecided;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="lea_id", unique=true, nullable=false)
    public Integer getLeaId() {
        return this.leaId;
    }
    
    public void setLeaId(Integer leaId) {
        this.leaId = leaId;
    }

    
    @Column(name="lea_usr_id", nullable=false)
    public int getLeaUsrId() {
        return this.leaUsrId;
    }
    
    public void setLeaUsrId(int leaUsrId) {
        this.leaUsrId = leaUsrId;
    }

    
    @Column(name="lea_ltp_id")
    public Integer getLeaLtpId() {
        return this.leaLtpId;
    }
    
    public void setLeaLtpId(Integer leaLtpId) {
        this.leaLtpId = leaLtpId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="lea_day", nullable=false, length=10)
    public Date getLeaDay() {
        return this.leaDay;
    }
    
    public void setLeaDay(Date leaDay) {
        this.leaDay = leaDay;
    }

    
    @Column(name="lea_reason", length=65535)
    public String getLeaReason() {
        return this.leaReason;
    }
    
    public void setLeaReason(String leaReason) {
        this.leaReason = leaReason;
    }

    
    @Column(name="lea_status")
    public Boolean getLeaStatus() {
        return this.leaStatus;
    }
    
    public void setLeaStatus(Boolean leaStatus) {
        this.leaStatus = leaStatus;
    }

    
    @Column(name="lea_who_decided")
    public Integer getLeaWhoDecided() {
        return this.leaWhoDecided;
    }
    
    public void setLeaWhoDecided(Integer leaWhoDecided) {
        this.leaWhoDecided = leaWhoDecided;
    }




}


