package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeaveTypes generated by hbm2java
 */
@Entity
@Table(name="leave_types"
    ,catalog="sbatko1"
)
public class LeaveTypes  implements java.io.Serializable {


     private Integer ltpId;
     private String ltpName;
     private String ltpCode;

    public LeaveTypes() {
    }

    public LeaveTypes(String ltpName, String ltpCode) {
       this.ltpName = ltpName;
       this.ltpCode = ltpCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ltp_id", unique=true, nullable=false)
    public Integer getLtpId() {
        return this.ltpId;
    }
    
    public void setLtpId(Integer ltpId) {
        this.ltpId = ltpId;
    }

    
    @Column(name="ltp_name", nullable=false, length=200)
    public String getLtpName() {
        return this.ltpName;
    }
    
    public void setLtpName(String ltpName) {
        this.ltpName = ltpName;
    }

    
    @Column(name="ltp_code", nullable=false, length=200)
    public String getLtpCode() {
        return this.ltpCode;
    }
    
    public void setLtpCode(String ltpCode) {
        this.ltpCode = ltpCode;
    }




}


