package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name="roles"
    ,catalog="sbatko1"
    , uniqueConstraints = @UniqueConstraint(columnNames="rol_code") 
)
public class Roles  implements java.io.Serializable {


     private Integer rolId;
     private String rolName;
     private String rolCode;

    public Roles() {
    }

    public Roles(String rolName, String rolCode) {
       this.rolName = rolName;
       this.rolCode = rolCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="rol_id", unique=true, nullable=false)
    public Integer getRolId() {
        return this.rolId;
    }
    
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }

    
    @Column(name="rol_name", nullable=false, length=100)
    public String getRolName() {
        return this.rolName;
    }
    
    public void setRolName(String rolName) {
        this.rolName = rolName;
    }

    
    @Column(name="rol_code", unique=true, nullable=false, length=100)
    public String getRolCode() {
        return this.rolCode;
    }
    
    public void setRolCode(String rolCode) {
        this.rolCode = rolCode;
    }




}


