package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name="tasks"
    ,catalog="sbatko1"
)
public class Tasks  implements java.io.Serializable {


     private Integer tskId;
     private String nazwa;
     private String tskDescription;
     private Date tskCreationDate;
     private int tskTime;
     private int tskUsrLeaderId;
     private int tskUsrWorkerId;
     private Integer tskTprId;

    public Tasks() {
    }

	
    public Tasks(String nazwa, Date tskCreationDate, int tskTime, int tskUsrLeaderId, int tskUsrWorkerId) {
        this.nazwa = nazwa;
        this.tskCreationDate = tskCreationDate;
        this.tskTime = tskTime;
        this.tskUsrLeaderId = tskUsrLeaderId;
        this.tskUsrWorkerId = tskUsrWorkerId;
    }
    public Tasks(String nazwa, String tskDescription, Date tskCreationDate, int tskTime, int tskUsrLeaderId, int tskUsrWorkerId, Integer tskTprId) {
       this.nazwa = nazwa;
       this.tskDescription = tskDescription;
       this.tskCreationDate = tskCreationDate;
       this.tskTime = tskTime;
       this.tskUsrLeaderId = tskUsrLeaderId;
       this.tskUsrWorkerId = tskUsrWorkerId;
       this.tskTprId = tskTprId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tsk_id", unique=true, nullable=false)
    public Integer getTskId() {
        return this.tskId;
    }
    
    public void setTskId(Integer tskId) {
        this.tskId = tskId;
    }

    
    @Column(name="nazwa", nullable=false, length=65535)
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    
    @Column(name="tsk_description", length=65535)
    public String getTskDescription() {
        return this.tskDescription;
    }
    
    public void setTskDescription(String tskDescription) {
        this.tskDescription = tskDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tsk_creation_date", nullable=false, length=19)
    public Date getTskCreationDate() {
        return this.tskCreationDate;
    }
    
    public void setTskCreationDate(Date tskCreationDate) {
        this.tskCreationDate = tskCreationDate;
    }

    
    @Column(name="tsk_time", nullable=false)
    public int getTskTime() {
        return this.tskTime;
    }
    
    public void setTskTime(int tskTime) {
        this.tskTime = tskTime;
    }

    
    @Column(name="tsk_usr_leader_id", nullable=false)
    public int getTskUsrLeaderId() {
        return this.tskUsrLeaderId;
    }
    
    public void setTskUsrLeaderId(int tskUsrLeaderId) {
        this.tskUsrLeaderId = tskUsrLeaderId;
    }

    
    @Column(name="tsk_usr_worker_id", nullable=false)
    public int getTskUsrWorkerId() {
        return this.tskUsrWorkerId;
    }
    
    public void setTskUsrWorkerId(int tskUsrWorkerId) {
        this.tskUsrWorkerId = tskUsrWorkerId;
    }

    
    @Column(name="tsk_tpr_id")
    public Integer getTskTprId() {
        return this.tskTprId;
    }
    
    public void setTskTprId(Integer tskTprId) {
        this.tskTprId = tskTprId;
    }




}


