package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TaskPriorities generated by hbm2java
 */
@Entity
@Table(name="task_priorities"
    ,catalog="sbatko1"
)
public class TaskPriorities  implements java.io.Serializable {


     private Integer tprId;
     private String tprName;
     private String tprCode;

    public TaskPriorities() {
    }

    public TaskPriorities(String tprName, String tprCode) {
       this.tprName = tprName;
       this.tprCode = tprCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tpr_id", unique=true, nullable=false)
    public Integer getTprId() {
        return this.tprId;
    }
    
    public void setTprId(Integer tprId) {
        this.tprId = tprId;
    }

    
    @Column(name="tpr_name", nullable=false, length=100)
    public String getTprName() {
        return this.tprName;
    }
    
    public void setTprName(String tprName) {
        this.tprName = tprName;
    }

    
    @Column(name="tpr_code", nullable=false, length=100)
    public String getTprCode() {
        return this.tprCode;
    }
    
    public void setTprCode(String tprCode) {
        this.tprCode = tprCode;
    }




}


