package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="sbatko1"
    , uniqueConstraints = @UniqueConstraint(columnNames="usr_login") 
)
public class Users  implements java.io.Serializable {


     private Integer usrId;
     private String usrLogin;
     private String usrPassword;
     private String usrEmail;
     private Integer usrBossUsrId;
     private int usrRolId;
     private Date usrDateCreation;
     private boolean usrActive;
     private Integer usrLeaveLimit;

    public Users() {
    }

	
    public Users(String usrLogin, String usrPassword, int usrRolId, boolean usrActive) {
        this.usrLogin = usrLogin;
        this.usrPassword = usrPassword;
        this.usrRolId = usrRolId;
        this.usrActive = usrActive;
    }
    public Users(String usrLogin, String usrPassword, String usrEmail, Integer usrBossUsrId, int usrRolId, Date usrDateCreation, boolean usrActive, Integer usrLeaveLimit) {
       this.usrLogin = usrLogin;
       this.usrPassword = usrPassword;
       this.usrEmail = usrEmail;
       this.usrBossUsrId = usrBossUsrId;
       this.usrRolId = usrRolId;
       this.usrDateCreation = usrDateCreation;
       this.usrActive = usrActive;
       this.usrLeaveLimit = usrLeaveLimit;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="usr_id", unique=true, nullable=false)
    public Integer getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(Integer usrId) {
        this.usrId = usrId;
    }

    
    @Column(name="usr_login", unique=true, nullable=false, length=100)
    public String getUsrLogin() {
        return this.usrLogin;
    }
    
    public void setUsrLogin(String usrLogin) {
        this.usrLogin = usrLogin;
    }

    
    @Column(name="usr_password", nullable=false, length=100)
    public String getUsrPassword() {
        return this.usrPassword;
    }
    
    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword;
    }

    
    @Column(name="usr_email", length=150)
    public String getUsrEmail() {
        return this.usrEmail;
    }
    
    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail;
    }

    
    @Column(name="usr_boss_usr_id")
    public Integer getUsrBossUsrId() {
        return this.usrBossUsrId;
    }
    
    public void setUsrBossUsrId(Integer usrBossUsrId) {
        this.usrBossUsrId = usrBossUsrId;
    }

    
    @Column(name="usr_rol_id", nullable=false)
    public int getUsrRolId() {
        return this.usrRolId;
    }
    
    public void setUsrRolId(int usrRolId) {
        this.usrRolId = usrRolId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="usr_date_creation", length=10)
    public Date getUsrDateCreation() {
        return this.usrDateCreation;
    }
    
    public void setUsrDateCreation(Date usrDateCreation) {
        this.usrDateCreation = usrDateCreation;
    }

    
    @Column(name="usr_active", nullable=false)
    public boolean isUsrActive() {
        return this.usrActive;
    }
    
    public void setUsrActive(boolean usrActive) {
        this.usrActive = usrActive;
    }

    
    @Column(name="usr_leave_limit")
    public Integer getUsrLeaveLimit() {
        return this.usrLeaveLimit;
    }
    
    public void setUsrLeaveLimit(Integer usrLeaveLimit) {
        this.usrLeaveLimit = usrLeaveLimit;
    }




}


