package com.hrm.db.model;
// Generated 2015-01-02 11:10:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkLogs generated by hbm2java
 */
@Entity
@Table(name="work_logs"
    ,catalog="sbatko1"
)
public class WorkLogs  implements java.io.Serializable {


     private int wloId;
     private int wloTskId;
     private int wloUsrId;
     private String wloComment;
     private Date wloDate;
     private double wloTime;

    public WorkLogs() {
    }

	
    public WorkLogs(int wloId, int wloTskId, int wloUsrId, Date wloDate, double wloTime) {
        this.wloId = wloId;
        this.wloTskId = wloTskId;
        this.wloUsrId = wloUsrId;
        this.wloDate = wloDate;
        this.wloTime = wloTime;
    }
    public WorkLogs(int wloId, int wloTskId, int wloUsrId, String wloComment, Date wloDate, double wloTime) {
       this.wloId = wloId;
       this.wloTskId = wloTskId;
       this.wloUsrId = wloUsrId;
       this.wloComment = wloComment;
       this.wloDate = wloDate;
       this.wloTime = wloTime;
    }
   
     @Id 

    
    @Column(name="wlo_id", unique=true, nullable=false)
    public int getWloId() {
        return this.wloId;
    }
    
    public void setWloId(int wloId) {
        this.wloId = wloId;
    }

    
    @Column(name="wlo_tsk_id", nullable=false)
    public int getWloTskId() {
        return this.wloTskId;
    }
    
    public void setWloTskId(int wloTskId) {
        this.wloTskId = wloTskId;
    }

    
    @Column(name="wlo_usr_id", nullable=false)
    public int getWloUsrId() {
        return this.wloUsrId;
    }
    
    public void setWloUsrId(int wloUsrId) {
        this.wloUsrId = wloUsrId;
    }

    
    @Column(name="wlo_comment", length=65535)
    public String getWloComment() {
        return this.wloComment;
    }
    
    public void setWloComment(String wloComment) {
        this.wloComment = wloComment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wlo_date", nullable=false, length=19)
    public Date getWloDate() {
        return this.wloDate;
    }
    
    public void setWloDate(Date wloDate) {
        this.wloDate = wloDate;
    }

    
    @Column(name="wlo_time", nullable=false, precision=22, scale=0)
    public double getWloTime() {
        return this.wloTime;
    }
    
    public void setWloTime(double wloTime) {
        this.wloTime = wloTime;
    }




}


